### ISSUE TITLE
Getting "panic: send on closed channel" when requesting from postman

### ISSUE THREAD

**Issue by SamOrozco** [SamOrozco/chaos_router#4]
When accepting any request through postman (everything else I have tried has been through the browser) an exception is thrown. 
```
panic: send on closed channel

goroutine 20 [running]:
go_chaos/tcp_server.ReadTcpRequestAsStringAsync.func1(0x597e00, 0xc0000940f8, 0xc000050360)
        C:/Users/samue/projects/go_chaos/tcp_server/tcp_util.go:40 +0xdc
created by go_chaos/tcp_server.ReadTcpRequestAsStringAsync
        C:/Users/samue/projects/go_chaos/tcp_server/tcp_util.go:35 +0x78

```

**Comment by SamOrozco** [comment]
Fixed the sending on closed channel issue. Realized that the post part was a user error. We really nead fallback rules
